[
  {
    id: "f4a1039.77816",
    type: "tab",
    label: "Line Bot JPY",
    disabled: false,
    info: ""
  },
  {
    id: "1cdf8c88.5fb8d3",
    type: "inject",
    z: "f4a1039.77816",
    name: "",
    topic: "",
    payload: "",
    payloadType: "date",
    repeat: "3600",
    crontab: "",
    once: false,
    onceDelay: 0.1,
    x: 220,
    y: 120,
    wires: [["e523d1ed.87656"]]
  },
  {
    id: "e523d1ed.87656",
    type: "http request",
    z: "f4a1039.77816",
    name: "",
    method: "GET",
    ret: "txt",
    url: "http://rate.bot.com.tw/xrt?Lang=zh-TW",
    tls: "",
    x: 410,
    y: 120,
    wires: [["cc67386b.69cc48"]]
  },
  {
    id: "cc67386b.69cc48",
    type: "html",
    z: "f4a1039.77816",
    name: "filter",
    property: "payload",
    outproperty: "payload",
    tag: ".rate-content-cash.text-right.print_hide",
    ret: "html",
    as: "single",
    x: 569,
    y: 120,
    wires: [["6f5c428c.c222ec"]]
  },
  {
    id: "6f5c428c.c222ec",
    type: "function",
    z: "f4a1039.77816",
    name: "Get JPY Currency",
    func:
      "var currency = 0.28;\n\nvar data = {\n    jpy: Number(msg.payload[15])\n}\n\nvar isLow =  flow.get('isLow') || false;\nmsg.payload = data\nif (data.jpy < currency && !isLow) {\n    isLow = true;\n    flow.set('isLow', isLow);\n    return msg;\n}\nif (data.jpy > currency && isLow) {\n    isLow = false;\n    flow.set('isLow', isLow);\n}",
    outputs: 1,
    noerr: 0,
    x: 754,
    y: 120,
    wires: [["ef3dd37a.900db", "3d5e1d3d.8d0e92"]]
  },
  {
    id: "3d5e1d3d.8d0e92",
    type: "debug",
    z: "f4a1039.77816",
    name: "",
    active: false,
    tosidebar: true,
    console: false,
    tostatus: false,
    complete: "payload",
    x: 1004,
    y: 120,
    wires: []
  },
  {
    id: "ef3dd37a.900db",
    type: "function",
    z: "f4a1039.77816",
    name: "傳送信息",
    func:
      "CHANNEL_ACCESS_TOKEN = 'Messaging API Token';\nUSER_ID = '使用者ID(不是Line ID)';\nmessage = {\n    type:'text',\n    text:'目前日圓匯率：'+msg.payload.jpy\n};\nheaders = {\n    'Content-Type': 'application/json; charset=UTF-8',\n    'Authorization': 'Bearer ' + CHANNEL_ACCESS_TOKEN,\n};\npayload = {\n    'to':  USER_ID,\n    'messages': [message]\n};\nmsg.headers = headers;\nmsg.payload = payload;\nreturn msg;",
    outputs: 1,
    noerr: 0,
    x: 994,
    y: 170,
    wires: [["1a1d9d91.e25812"]]
  },
  {
    id: "1a1d9d91.e25812",
    type: "http request",
    z: "f4a1039.77816",
    name: "Messaging API 傳送",
    method: "POST",
    ret: "txt",
    url: "https://api.line.me/v2/bot/message/push",
    tls: "",
    x: 1216,
    y: 170,
    wires: [[]]
  },
  {
    id: "115048dd.aa6ef7",
    type: "http in",
    z: "f4a1039.77816",
    name: "Messaging API 接收",
    url: "/line_hook",
    method: "post",
    upload: false,
    swaggerDoc: "",
    x: 239,
    y: 203,
    wires: [["c3a26b18.b658b8"]]
  },
  {
    id: "c3a26b18.b658b8",
    type: "debug",
    z: "f4a1039.77816",
    name: "",
    active: true,
    tosidebar: true,
    console: false,
    tostatus: false,
    complete: "false",
    x: 434,
    y: 203,
    wires: []
  },
  {
    id: "9035f1cb.02bb5",
    type: "inject",
    z: "f4a1039.77816",
    name: "發送測試信息",
    topic: "",
    payload: '{"jpy":"測試信息"}',
    payloadType: "json",
    repeat: "",
    crontab: "",
    once: false,
    onceDelay: 0.1,
    x: 732,
    y: 202,
    wires: [["ef3dd37a.900db"]]
  }
];
